version: 2.1

jobs:
  lint:
    docker:
      - image: golangci/golangci-lint:v1.55-alpine
    steps:
      - checkout
      - run: golangci-lint run --timeout=3m 
  test:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run: go test -v -race ./...

workflows:
  sample: 
    jobs:
      - lint
      - test